import { Perfil } from "../app/api/perfiles/route";
export async function PerfilesData(): Promise<Perfil[]> {
  return [
    { id: "perf_1", name: "Perfil 1", url: "" },
    { id: "perf_2", name: "Perfil 2", url: "" },
    { id: "perf_3", name: "Perfil 3", url: "" },
    { id: "perf_4", name: "Perfil 4", url: "" },
    { id: "perf_5", name: "Perfil 5", url: "" },
    { id: "perf_6", name: "Perfil 6", url: "" },
    { id: "perf_7", name: "Perfil 7", url: "" },
    { id: "perf_8", name: "Perfil 8", url: "" },
    { id: "perf_9", name: "Perfil 9", url: "" },
    { id: "perf_10", name: "Perfil 10", url: "" },
    { id: "perf_11", name: "Perfil 11", url: "" },
    { id: "perf_12", name: "Perfil 12", url: "" },
    { id: "perf_13", name: "Perfil 13", url: "" },
    { id: "perf_14", name: "Perfil 14", url: "" },
    { id: "perf_15", name: "Perfil 15", url: "" },
    { id: "perf_16", name: "Perfil 16", url: "" },
    { id: "perf_17", name: "Perfil 17", url: "" },
    { id: "perf_18", name: "Perfil 18", url: "" },
    { id: "perf_19", name: "Perfil 19", url: "" },
    { id: "perf_20", name: "Perfil 20", url: "" },
    { id: "perf_21", name: "Perfil 21", url: "" },
    { id: "perf_22", name: "Perfil 22", url: "" },
    { id: "perf_23", name: "Perfil 23", url: "" },
    { id: "perf_24", name: "Perfil 24", url: "" },
    { id: "perf_25", name: "Perfil 25", url: "" },
    { id: "perf_26", name: "Perfil 26", url: "" },
    { id: "perf_27", name: "Perfil 27", url: "" },
    { id: "perf_28", name: "Perfil 28", url: "" },
    { id: "perf_29", name: "Perfil 29", url: "" },
    { id: "perf_30", name: "Perfil 30", url: "" },
    { id: "perf_31", name: "Perfil 31", url: "" },
    { id: "perf_32", name: "Perfil 32", url: "" },
    { id: "perf_33", name: "Perfil 33", url: "" },
    { id: "perf_34", name: "Perfil 34", url: "" },
    { id: "perf_35", name: "Perfil 35", url: "" },
    { id: "perf_36", name: "Perfil 36", url: "" },
    { id: "perf_37", name: "Perfil 37", url: "" },
    { id: "perf_38", name: "Perfil 38", url: "" },
  ];
}
