export async function getSectorItemsData() {
  return {
    financial: [
      "Banco",
      "Corporación Financiera",
      "Compañía de Financiamiento",
      "Cooperativa Financiera",
      "Fiduciaria",
      "Administradora de Pensiones y Cesantías",
      "Compañía de Seguros",
      "Compañía de Reaseguros",
      "Cooperativa de Seguros",
      "Comisionista de Bolsa",
      "Bolsa de Valores",
      "Agencia de Seguros",
      "Sociedad de Capitalización",
    ],
    solidarity: [
      "ONG",
      "Empresa social",
      "Fintech",
      "Agencia de cooperación internacional",
      "Organismo unilateral",
      "Empresa de desarrollo internacional",
      "Investigador (a)",
      "Docente",
      "Estudiante",
      "Entidad pública del orden nacional",
      "Entidad pública del orden territorial",
      "Otros u otras",
    ],
    otherEntities: [
      "Asociación mutual",
      "Fondo de empleado",
      "Cooperativas de ahorro y crédito",
      "Cooperativa multiactiva e integral sin sección de ahorro y crédito",
      "Cooperativa especializada en actividades diferentes a la financiera",
      "Precooperativa",
      "Cooperativa de trabajo asociado",
      "Institución auxiliar de la economía solidaria",
    ],
  };
}
